title: Walking Machine
email: walking@ens.etsmtl.ca
twitter_username: WM_ETS
github_username: wmets
theme: alpha
jekyll-mentions:
  base_url: https://twitter.com
exclude: ['README.md','CNAME','vendor','Gemfile','Gemfile.lock']
markdown: kramdown
gems:
  - jekyll-feed

t:
  EN:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/en/about"
    contact:
      name: "Contact-us"
      url: "/en/contact"
    team:
      name: "Our team"
      url: "/en/team"
    comp:
      name: "Competition"
      url: "/en/competition"
    project:
      name: "Project"
      url: "/en/project"
    partener:
      name: "Partener"
      url: "/en/partener"
    robot:
      name: "Robot"
      url: "/en/robot"
    blog:
      name: "Blog"
      url: "/en/blog"
    media:
      name: "Media"
      url: "/en/media"

  FR:
    home:
      name: "Accueil"
      url: "/fr/"
    about:
      name: "À propos"
      url: "/fr/about/"
    contact:
      name: "Nous contacter"
      url: "/fr/contact"
    team:
      name: "Notre équipe"
      url: "/fr/equipe"
    comp:
      name: "Compétition"
      url: "/fr/compe"
